apiVersion: apps/v1
kind: Deployment
metadata:
  name: goba_content
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goba_content
  template:
    metadata:
      labels:
        app: goba_content
    spec:
      containers:
      - name: goba_content
        image: goba_content:latest
        ports:
        - containerPort: 8081